import React from 'react';
import Footer from '../components/Footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en" style={{ padding: 0, margin: 0 }}>
      <body style={{ padding: 0, margin: 0 }}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;